name: Staging Deploy, Test, and Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-and-test-staging:
    name: Deploy to Staging and Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ステージングサーバーにSSH接続してデプロイ
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSHE_SSH_KEY }}
          script: |
            cd /app/shota_nishinaga
            git pull origin main
            bash ./deploy.sh shota_nishinaga

      # 3. ステージング環境に対してE2Eテストを実行
      - name: Run E2E Tests on Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSHE_SSH_KEY }}
          script: |
            echo "Running E2E tests..."
            cd /ci
            npx cypress run --spec "cypress/e2e/shota_nishinaga.cy.js"

  deploy-to-production:
    name: Deploy to Production
    needs: deploy-and-test-staging # deploy-and-test-stagingジョブの成功を待つ
    runs-on: ubuntu-latest
    steps:
      # 1. ソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 本番サーバーにSSH接続してデプロイ
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAIN_SSH_HOST }}
          port: ${{ secrets.MAIN_SSH_PORT }}
          username: ${{ secrets.MAIN_SSH_USER }}
          key: ${{ secrets.MAIN_SSHE_SSH_KEY }}
          script: |
            echo "Deploying to production..."
            cd /app/shota_nishinaga
            git pull origin main
            bash ./deploy.sh shota_nishinaga
